#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h> 

// The model's C file, generated by onnx2c, is specified at compile time.
#if defined(MODEL_HEADER)
    #include MODEL_HEADER
#else
    #error "MODEL_HEADER not defined. Please compile using the Makefile."
#endif

// The new header file containing the embedded images and labels.
#include "test_images.h"

#define NUM_CLASSES 10

// A function to print the logit array.
void print_logits(float predictions[1][NUM_CLASSES]) {
    printf("  Logits: [");
    for (int i = 0; i < NUM_CLASSES; ++i) {
        printf("%+9.6f", predictions[0][i]);
        if (i < NUM_CLASSES - 1) {
            printf(", ");
        }
    }
    printf("]\n");
}

// A function to find the predicted class from the logits.
int get_predicted_class(float predictions[1][NUM_CLASSES]) {
    int predicted_class = -1;
    float max_prob = -1e9; // A very small initial value
    for (int i = 0; i < NUM_CLASSES; ++i) {
        if (predictions[0][i] > max_prob) {
            max_prob = predictions[0][i];
            predicted_class = i;
        }
    }
    return predicted_class;
}

int main() {
    // We no longer need file pointers or a pointer for input_data.
    // 'input_data' is now the 'test_images_data' constant from the header.
    float (*predictions)[NUM_CLASSES];

    // Allocate memory only for the model's output predictions.
    predictions = malloc(NUM_CLASSES * sizeof(float));
    if (!predictions) {
        perror("Failed to allocate memory for predictions");
        return 1;
    }

    // The file opening logic is no longer needed.

    printf("--- Testing Model: %s ---\n", MODEL_NAME);
    double total_time_spent = 0.0;

    // Process all images defined in the header file.
    // The loop's condition NUM_TEST_IMAGES comes directly from test_images.h.
    for (int i = 0; i < NUM_TEST_IMAGES; ++i) {
        
        // Reading from files with fread is no longer needed.
        // We will use the data directly from the constant arrays.

        // --- Timing measurement ---
        struct timespec start, end;
        clock_gettime(CLOCK_MONOTONIC, &start);

        // Run inference using the i-th image from the embedded array.
        // The entry function expects a pointer to a [3][32][32] array.
        // &test_images_data[i] provides exactly that type of pointer.
        entry((const float (*)[3][32][32])&test_images_data[i], (float (*)[10])predictions);

        clock_gettime(CLOCK_MONOTONIC, &end);
        total_time_spent += (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1e9;
        // --- End of timing ---

        int predicted_class = get_predicted_class((float (*)[10])predictions);
        
        // Get the true label from our embedded label array.
        int32_t true_label = test_image_labels[i];

        printf("\n--- Results for Image %d ---\n", i);
        print_logits((float (*)[10])predictions);
        printf("  Predicted Class: %d, True Label: %d\n", predicted_class, true_label);
    }

    printf("\n--------------------------------------------------\n");
    // Use NUM_TEST_IMAGES from the header for the final report.
    printf("Total inference time for %d images: %.6f seconds\n", NUM_TEST_IMAGES, total_time_spent);
    printf("--------------------------------------------------\n");

    // Cleanup: close files and free memory.
    // No more files to close or input_data to free.
    free(predictions);

    return 0;
}